# Generated by Django 2.0.6 on 2019-05-20 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NTWebsite', '0034_auto_20190518_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('Object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章')),
                ('SourceUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者')),
                ('TargetUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='TUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者')),
            ],
            options={
                'verbose_name': '评论通知',
                'verbose_name_plural': '评论通知中心',
            },
        ),
    ]
