# Generated by Django 2.0.6 on 2019-05-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0035_auto_20190520_1758'),
        ('NTNotification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkNotification',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('ObjectID', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.UserLink', verbose_name='被关注者')),
            ],
            options={
                'verbose_name_plural': '关注通知中心',
                'verbose_name': '关注通知',
            },
        ),
        migrations.CreateModel(
            name='RollCallNotification',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('Type', models.CharField(default='Comment', max_length=10, verbose_name='通知类型')),
                ('RollCallObject', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.RollCallInfo', verbose_name='点名')),
                ('TopicObject', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章专题')),
            ],
            options={
                'verbose_name_plural': '更新通知中心',
                'verbose_name': '更新通知',
            },
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='TargetUser',
        ),
        migrations.AddField(
            model_name='commentnotification',
            name='Type',
            field=models.CharField(default='Comment', max_length=10, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='commentnotification',
            name='Object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.CommentInfo', verbose_name='文章'),
        ),
    ]
