# Generated by Django 2.0.6 on 2019-05-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0035_auto_20190520_1758'),
        ('NTNotification', '0002_auto_20190521_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishNotification',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('Type', models.CharField(default='Comment', max_length=10, verbose_name='通知类型')),
                ('RollCallObject', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.RollCallInfo', verbose_name='点名')),
                ('TopicObject', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章专题')),
            ],
            options={
                'verbose_name': '更新通知',
                'verbose_name_plural': '更新通知中心',
            },
        ),
        migrations.AlterModelOptions(
            name='rollcallnotification',
            options={'verbose_name': '点名通知', 'verbose_name_plural': '点名通知中心'},
        ),
        migrations.RenameField(
            model_name='rollcallnotification',
            old_name='RollCallObject',
            new_name='RCObject',
        ),
        migrations.RemoveField(
            model_name='rollcallnotification',
            name='TopicObject',
        ),
        migrations.AddField(
            model_name='rollcallnotification',
            name='RCDObject',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.RollCallDialogue', verbose_name='点名对话'),
        ),
    ]
