# Generated by Django 2.0.6 on 2019-05-21 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NTNotification', '0003_auto_20190521_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnotification',
            name='SourceUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='CSourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者'),
        ),
        migrations.AddField(
            model_name='commentnotification',
            name='TargetUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='CTargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者'),
        ),
        migrations.AddField(
            model_name='linknotification',
            name='SourceUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='LSourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者'),
        ),
        migrations.AddField(
            model_name='linknotification',
            name='TargetUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='LTargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者'),
        ),
        migrations.AddField(
            model_name='publishnotification',
            name='SourceUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='PSourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者'),
        ),
        migrations.AddField(
            model_name='publishnotification',
            name='TargetUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='PTargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者'),
        ),
        migrations.AddField(
            model_name='rollcallnotification',
            name='SourceUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='RSourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者'),
        ),
        migrations.AddField(
            model_name='rollcallnotification',
            name='TargetUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='RTargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者'),
        ),
        migrations.AlterField(
            model_name='commentnotification',
            name='Type',
            field=models.CharField(default='Comment', max_length=15, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='publishnotification',
            name='Type',
            field=models.CharField(default='Comment', max_length=15, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='rollcallnotification',
            name='Type',
            field=models.CharField(default='Comment', max_length=15, verbose_name='通知类型'),
        ),
    ]
