# Generated by Django 2.0.6 on 2019-05-21 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0035_auto_20190520_1758'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NTNotification', '0004_auto_20190521_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttitudeNotification',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('Type', models.CharField(default='T', max_length=15, verbose_name='通知类型')),
                ('SourceUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ASourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者')),
                ('TObject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.CommentInfo', verbose_name='评论')),
                ('TargetUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ATargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者')),
            ],
            options={
                'verbose_name_plural': '评论通知中心',
                'verbose_name': '评论通知',
            },
        ),
        migrations.AddField(
            model_name='linknotification',
            name='Type',
            field=models.CharField(default='', max_length=15, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='commentnotification',
            name='Object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.CommentInfo', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='commentnotification',
            name='Type',
            field=models.CharField(default='C', max_length=15, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='publishnotification',
            name='Type',
            field=models.CharField(default='', max_length=15, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='rollcallnotification',
            name='Type',
            field=models.CharField(default='R', max_length=15, verbose_name='通知类型'),
        ),
    ]
