# Generated by Django 2.0.6 on 2019-05-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTNotification', '0005_auto_20190521_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attitudenotification',
            options={'verbose_name': '赞/怼通知', 'verbose_name_plural': '赞/怼通知中心'},
        ),
    ]
