# Generated by Django 2.0.6 on 2019-05-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0035_auto_20190520_1758'),
        ('NTNotification', '0006_auto_20190521_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='attitudenotification',
            name='CObject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.CommentInfo', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='attitudenotification',
            name='TObject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章'),
        ),
    ]
