# Generated by Django 2.0.6 on 2019-05-21 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0035_auto_20190520_1758'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NTNotification', '0008_auto_20190521_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttitudeNotification',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('Type', models.CharField(default='T', max_length=15, verbose_name='通知类型')),
                ('Comment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.CommentInfo', verbose_name='评论')),
                ('SourceUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='CASourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者')),
                ('TargetUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='CATargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者')),
            ],
            options={
                'verbose_name_plural': '赞/怼通知中心',
                'verbose_name': '赞/怼通知',
            },
        ),
        migrations.CreateModel(
            name='TopicAttitudeNotification',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('Type', models.CharField(default='T', max_length=15, verbose_name='通知类型')),
                ('SourceUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='TASourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者')),
                ('TargetUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='TATargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者')),
                ('Topic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章')),
            ],
            options={
                'verbose_name_plural': '赞/怼通知中心',
                'verbose_name': '赞/怼通知',
            },
        ),
        migrations.RemoveField(
            model_name='attitudenotification',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='attitudenotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='attitudenotification',
            name='TargetUser',
        ),
        migrations.RemoveField(
            model_name='attitudenotification',
            name='Topic',
        ),
        migrations.DeleteModel(
            name='AttitudeNotification',
        ),
    ]
