# Generated by Django 2.0.6 on 2019-05-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTNotification', '0009_auto_20190521_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentattitudenotification',
            old_name='Comment',
            new_name='ObjectID',
        ),
        migrations.RenameField(
            model_name='topicattitudenotification',
            old_name='Topic',
            new_name='ObjectID',
        ),
    ]
