# Generated by Django 2.0.6 on 2019-05-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTNotification', '0010_auto_20190521_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentattitudenotification',
            old_name='ObjectID',
            new_name='Object',
        ),
        migrations.RenameField(
            model_name='topicattitudenotification',
            old_name='ObjectID',
            new_name='Object',
        ),
    ]
