# Generated by Django 2.0.6 on 2019-05-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTNotification', '0011_auto_20190521_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentattitudenotification',
            options={'verbose_name': '评论赞/怼通知', 'verbose_name_plural': '评论赞/怼通知中心'},
        ),
        migrations.AlterModelOptions(
            name='topicattitudenotification',
            options={'verbose_name': '文章赞/怼通知', 'verbose_name_plural': '文章赞/怼通知中心'},
        ),
    ]
