# Generated by Django 2.0.6 on 2019-05-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NTWebsite', '0035_auto_20190520_1758'),
        ('NTNotification', '0012_auto_20190521_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('ID', models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('Type', models.CharField(max_length=15, verbose_name='通知类型')),
                ('CAObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CAObject', to='NTWebsite.CommentInfo', verbose_name='评论')),
                ('CObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CObject', to='NTWebsite.CommentInfo', verbose_name='评论')),
                ('LObject', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LObject', to='NTWebsite.UserLink', verbose_name='被关注者')),
                ('RDObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RDObject', to='NTWebsite.RollCallDialogue', verbose_name='点名对话')),
                ('RObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RObject', to='NTWebsite.RollCallInfo', verbose_name='点名')),
                ('RPObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RPObject', to='NTWebsite.RollCallInfo', verbose_name='点名')),
                ('SourceUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NSourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者')),
                ('TAObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TAObject', to='NTWebsite.TopicInfo', verbose_name='文章')),
                ('TPObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TPObject', to='NTWebsite.TopicInfo', verbose_name='文章专题')),
                ('TargetUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NTargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentattitudenotification',
            name='Object',
        ),
        migrations.RemoveField(
            model_name='commentattitudenotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='commentattitudenotification',
            name='TargetUser',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='Object',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='TargetUser',
        ),
        migrations.RemoveField(
            model_name='linknotification',
            name='ObjectID',
        ),
        migrations.RemoveField(
            model_name='linknotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='linknotification',
            name='TargetUser',
        ),
        migrations.RemoveField(
            model_name='publishnotification',
            name='RollCallObject',
        ),
        migrations.RemoveField(
            model_name='publishnotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='publishnotification',
            name='TargetUser',
        ),
        migrations.RemoveField(
            model_name='publishnotification',
            name='TopicObject',
        ),
        migrations.RemoveField(
            model_name='rollcallnotification',
            name='RCDObject',
        ),
        migrations.RemoveField(
            model_name='rollcallnotification',
            name='RCObject',
        ),
        migrations.RemoveField(
            model_name='rollcallnotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='rollcallnotification',
            name='TargetUser',
        ),
        migrations.RemoveField(
            model_name='topicattitudenotification',
            name='Object',
        ),
        migrations.RemoveField(
            model_name='topicattitudenotification',
            name='SourceUser',
        ),
        migrations.RemoveField(
            model_name='topicattitudenotification',
            name='TargetUser',
        ),
        migrations.DeleteModel(
            name='CommentAttitudeNotification',
        ),
        migrations.DeleteModel(
            name='CommentNotification',
        ),
        migrations.DeleteModel(
            name='LinkNotification',
        ),
        migrations.DeleteModel(
            name='PublishNotification',
        ),
        migrations.DeleteModel(
            name='RollCallNotification',
        ),
        migrations.DeleteModel(
            name='TopicAttitudeNotification',
        ),
    ]
