# Generated by Django 2.0.6 on 2019-02-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0002_auto_20190211_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentinfo',
            old_name='Comment',
            new_name='Content',
        ),
    ]
