# Generated by Django 2.0.6 on 2019-02-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0003_auto_20190211_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollcalldialogue',
            old_name='Reply',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='rollcallinfo',
            old_name='ID',
            new_name='ObjectID',
        ),
        migrations.RemoveField(
            model_name='rollcalldialogue',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='rollcalldialogue',
            name='Query',
        ),
        migrations.AddField(
            model_name='rollcalldialogue',
            name='Publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='RollCallDialogue_User', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='rollcalldialogue',
            name='RollCallID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.RollCallInfo', verbose_name='点名ID'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='Enforceder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='BlackList_User', to=settings.AUTH_USER_MODEL, verbose_name='被添加用户'),
        ),
    ]
