# Generated by Django 2.0.6 on 2019-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0004_auto_20190215_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollcallinfo',
            name='Read',
        ),
        migrations.AddField(
            model_name='rollcallinfo',
            name='Collect',
            field=models.IntegerField(default=0, verbose_name='关注度'),
        ),
        migrations.AddField(
            model_name='rollcallinfo',
            name='Comment',
            field=models.IntegerField(default=0, verbose_name='活跃度'),
        ),
        migrations.AddField(
            model_name='rollcallinfo',
            name='Hot',
            field=models.IntegerField(default=0, verbose_name='点名热度'),
        ),
        migrations.AddField(
            model_name='rollcallinfo',
            name='Recommend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='推荐度'),
        ),
    ]
