# Generated by Django 2.0.6 on 2019-02-19 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0005_auto_20190215_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollcalldialogue',
            name='id',
        ),
        migrations.AddField(
            model_name='rollcalldialogue',
            name='DialogueID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='对话ID'),
        ),
    ]
