# Generated by Django 2.0.6 on 2019-02-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0006_auto_20190219_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollcalldialogue',
            old_name='DialogueID',
            new_name='ObjectIDID',
        ),
    ]
