# Generated by Django 2.0.6 on 2019-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0008_auto_20190219_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollcalldialogue',
            name='Display',
            field=models.CharField(default='', max_length=10, verbose_name='显示位置'),
        ),
    ]
