# Generated by Django 2.0.6 on 2019-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0010_auto_20190305_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollcallinfo',
            name='Share',
            field=models.IntegerField(default=0, verbose_name='分享'),
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='Share',
            field=models.IntegerField(default=0, verbose_name='分享'),
        ),
    ]
