# Generated by Django 2.0.6 on 2019-03-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0011_auto_20190308_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparams',
            name='CommonPageLimit',
            field=models.IntegerField(default=10, verbose_name='通用分页限制'),
        ),
    ]
