# Generated by Django 2.0.6 on 2019-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0016_auto_20190426_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='Cover',
            field=models.ImageField(blank=True, default='', upload_to='Cover', verbose_name='封面'),
        ),
    ]
