# Generated by Django 2.0.6 on 2019-05-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0017_auto_20190426_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparams',
            name='IndexURL',
            field=models.CharField(default='/Topic/List/0/LE/1', max_length=200, verbose_name='首页URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Avatar',
            field=models.TextField(blank=True, default='DefaultLogo.jpg', max_length=1000, verbose_name='头像URL'),
        ),
    ]
