# Generated by Django 2.0.6 on 2019-05-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0020_auto_20190506_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='EditDate',
            field=models.DateField(auto_now=True, verbose_name='编辑时间'),
        ),
    ]
