# Generated by Django 2.0.6 on 2019-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0021_auto_20190506_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicinfo',
            name='EditDate',
        ),
        migrations.AddField(
            model_name='topicinfo',
            name='EditTime',
            field=models.DateTimeField(auto_now=True, verbose_name='编辑时间'),
        ),
    ]
