# Generated by Django 2.0.6 on 2019-05-06 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0022_auto_20190506_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='CreateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
