# Generated by Django 2.0.6 on 2019-05-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0023_auto_20190506_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attitude',
            options={'verbose_name': '赞/怼统计', 'verbose_name_plural': '5.赞/怼统计'},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': '黑名单记录', 'verbose_name_plural': '11.黑名单'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '收藏关注统计', 'verbose_name_plural': '8.收藏关注统计'},
        ),
        migrations.AlterModelOptions(
            name='commentinfo',
            options={'verbose_name': '评论统计', 'verbose_name_plural': '1.评论统计'},
        ),
        migrations.AlterModelOptions(
            name='configparams',
            options={'verbose_name': '参数配置表', 'verbose_name_plural': '2.参数配置表'},
        ),
        migrations.AlterModelOptions(
            name='filterquerystring',
            options={'verbose_name': '过滤器', 'verbose_name_plural': '4.URL过滤器'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '通知', 'verbose_name_plural': '10.通知中心'},
        ),
        migrations.AlterModelOptions(
            name='preferredconfigname',
            options={'verbose_name': '配置设置', 'verbose_name_plural': '3.配置设置'},
        ),
        migrations.AlterModelOptions(
            name='publisherlist',
            options={'verbose_name': '推荐用户', 'verbose_name_plural': '9.推荐用户表'},
        ),
        migrations.AlterModelOptions(
            name='readsip',
            options={'verbose_name': '访问统计', 'verbose_name_plural': '6.访问统计'},
        ),
        migrations.AlterModelOptions(
            name='rollcalldialogue',
            options={'verbose_name': '对话记录', 'verbose_name_plural': '14.点名对话统计'},
        ),
        migrations.AlterModelOptions(
            name='rollcallinfo',
            options={'verbose_name': '点名信息', 'verbose_name_plural': '13.点名统计'},
        ),
        migrations.AlterModelOptions(
            name='searchindex',
            options={'verbose_name': '全局索引', 'verbose_name_plural': '15.搜索索引'},
        ),
        migrations.AlterModelOptions(
            name='tipoffbox',
            options={'verbose_name': '举报统计', 'verbose_name_plural': '12.举报统计'},
        ),
        migrations.AlterModelOptions(
            name='topiccategoryinfo',
            options={'verbose_name': '类目', 'verbose_name_plural': '17.文章分类'},
        ),
        migrations.AlterModelOptions(
            name='topicinfo',
            options={'verbose_name': '文章内容', 'verbose_name_plural': '18.文章内容'},
        ),
        migrations.AlterModelOptions(
            name='topicthemeinfo',
            options={'verbose_name': '标签', 'verbose_name_plural': '16.文章标签'},
        ),
        migrations.AlterModelOptions(
            name='userlink',
            options={'verbose_name': '用户链接统计', 'verbose_name_plural': '7.用户链接统计'},
        ),
        migrations.AlterField(
            model_name='filterquerystring',
            name='MethodString',
            field=models.CharField(default='', max_length=200, verbose_name='匹配方法'),
        ),
        migrations.AlterField(
            model_name='filterquerystring',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='过滤器关键'),
        ),
        migrations.AlterField(
            model_name='preferredconfigname',
            name='Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.ConfigParams', to_field='Name', verbose_name='目前配置'),
        ),
        migrations.AlterField(
            model_name='topicthemeinfo',
            name='Name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='标签名称'),
        ),
    ]
