# Generated by Django 2.0.6 on 2019-05-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0024_auto_20190506_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='ID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='黑名单ID'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='CommentID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='评论ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='通知ID'),
        ),
        migrations.AlterField(
            model_name='rollcalldialogue',
            name='ObjectID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='对话ID'),
        ),
        migrations.AlterField(
            model_name='rollcallinfo',
            name='ObjectID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='点名ID'),
        ),
        migrations.AlterField(
            model_name='topicinfo',
            name='ObjectID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='文章ID'),
        ),
    ]
