# Generated by Django 2.0.6 on 2019-05-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0026_auto_20190515_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FoucusCount',
            new_name='FocusCount',
        ),
    ]
