# Generated by Django 2.0.6 on 2019-05-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0027_auto_20190515_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterquerystring',
            name='Name',
            field=models.CharField(max_length=100, unique=True, verbose_name='过滤器关键'),
        ),
    ]
