# Generated by Django 2.0.6 on 2019-05-16 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0028_auto_20190516_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circusee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollectTime', models.DateField(auto_now=True, verbose_name='时间')),
                ('ObjectID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.RollCallInfo', verbose_name='点名ID')),
                ('Publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '8.围观统计',
                'verbose_name': '围观统计',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollectTime', models.DateField(auto_now=True, verbose_name='时间')),
                ('ObjectID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章ID')),
                ('Publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '8.收藏统计',
                'verbose_name': '收藏统计',
            },
        ),
        migrations.CreateModel(
            name='CommentAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point', models.IntegerField(verbose_name='立场代码')),
                ('EditTime', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('Type', models.CharField(blank=True, max_length=30, verbose_name='类型')),
                ('ObjectID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.CommentInfo', verbose_name='评论ID')),
                ('Publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '5.评论赞/怼统计',
                'verbose_name': '评论赞/怼统计',
            },
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollectTime', models.DateField(auto_now=True, verbose_name='时间')),
                ('ObjectID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='专题ID')),
                ('Publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '8.关注统计',
                'verbose_name': '关注统计',
            },
        ),
        migrations.CreateModel(
            name='TopicAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point', models.IntegerField(verbose_name='立场代码')),
                ('EditTime', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('Type', models.CharField(blank=True, max_length=30, verbose_name='类型')),
                ('ObjectID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章ID')),
                ('Publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '5.文章赞/怼统计',
                'verbose_name': '文章赞/怼统计',
            },
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='Publisher',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Attitude',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
