# Generated by Django 2.0.6 on 2019-05-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0030_auto_20190516_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentinfo',
            name='CommentID',
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='TopicID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='ObjectID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='评论ID'),
        ),
    ]
