# Generated by Django 2.0.6 on 2019-05-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0031_auto_20190516_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='ObjectID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
