# Generated by Django 2.0.6 on 2019-05-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0032_auto_20190518_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattitude',
            name='ObjectID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.CommentInfo', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='TopicID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='topicattitude',
            name='ObjectID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NTWebsite.TopicInfo', verbose_name='文章'),
        ),
    ]
