# Generated by Django 2.0.6 on 2019-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0033_auto_20190518_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circusee',
            name='CollectTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='CollectTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='commentattitude',
            name='EditTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='EditDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='concern',
            name='CollectTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='readsip',
            name='EditDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='tipoffbox',
            name='EditDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='topicattitude',
            name='EditTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='LinkTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
