# Generated by Django 2.0.6 on 2019-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0034_auto_20190518_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MessageCount',
            field=models.IntegerField(default=0, verbose_name='未读消息数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='NotificationCount',
            field=models.IntegerField(default=0, verbose_name='未读通知数量'),
        ),
    ]
