# Generated by Django 2.0.6 on 2019-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailBody',
            fields=[
                ('Sence', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='发送场景')),
                ('Title', models.CharField(max_length=50, verbose_name='邮件标题')),
                ('Massage', models.CharField(max_length=100, verbose_name='邮件内容')),
                ('Html', models.CharField(max_length=1000, verbose_name='邮件HTML')),
            ],
            options={
                'verbose_name_plural': '邮件模板',
                'verbose_name': '邮件模板',
            },
        ),
    ]
