# Generated by Django 2.0.6 on 2019-05-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTMail', '0002_auto_20190530_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailbody',
            old_name='Sence',
            new_name='Scene',
        ),
    ]
