# Generated by Django 2.0.6 on 2019-05-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTMail', '0003_auto_20190530_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailbody',
            old_name='Massage',
            new_name='Message',
        ),
    ]
