# Generated by Django 2.0.6 on 2019-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTMail', '0004_auto_20190530_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbody',
            name='Html',
            field=models.TextField(default='', max_length=1000, verbose_name='邮件HTML'),
        ),
    ]
